<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ChatRoom.aspx.cs" Inherits="ChatRoom" MasterPageFile="~/Master Page/MasterPage.master" Title="Chat Room" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">

     <style type="text/css">
        .container {
            background-color: #99CCFF;
            border: thick solid #808080;
             width: 50vw;
            height: 63vh;
            position: absolute;
            top: 1vh;
            left:2vw;  
        }
        .discussion
        {
           position: absolute; 
            top: 15vh; 
            left:6vw; 
            height:40vh; 
            max-height:40vh;
            width:35vw; 
            max-width:35vw; 
            overflow:scroll;
        }
      
      
    </style>

   </asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="cphLeft" Runat="Server">
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="cphContent" Runat="Server">
      <div class="container">   
        <input type="text" id="message" style="position: absolute; top: 5vh; left:6vw;"/>
        <input type="button" id="sendmessage" value="Send" style="position: absolute; top: 10vh; left:6vw;" />
        <input type="hidden" id="displayname" style="position: absolute; top: 15vh; left:6vw;" />
       <ul id="discussion" class="discussion">
        </ul> 
    </div>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-2.2.3.min.js" ></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.--> 
    <script type="text/javascript">

      $(function () {
            $('input').keydown(function (e) {
                if (e.keyCode == 13) {
                    $("input[value='Send']").focus().click();
                    return false;
                }
            });
        });
        $(function () {
            // Declare a proxy to reference the hub. 
            var chat = $.connection.chatHub;
            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (name, message) {
                // Html encode display name and message. 
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page. 
                $('#discussion').append('<li><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
                //Move the scrollbar of the discussion window at the bottom
                $('.discussion').scrollTop($('.discussion')[0].scrollHeight);
            };
          

            // Get the user name and store it to prepend to messages.
            $('#displayname').val('<%=Session["UserName"]%>');
            // Set initial focus to message input box.  
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub. 
                    chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment. 
                    $('#message').val('').focus();
                });
            });
        });

       

    </script>

      <a href="Main.aspx" style="position:absolute; left:42vw; top:66vh">Back to Main page</a>
           

    </asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="cphRight" Runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="cphFooter" Runat="Server">
</asp:Content>
